//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dyClawler.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class crawlerconfigconfiguration
    {
        public int ID { get; set; }
        public string ConfigconfigurationName { get; set; }
        public string ConfigconfigurationValue { get; set; }
        public int ConfigconfigurationKey { get; set; }
        public DateTime DataCreateTime { get; set; }
        public bool IsEnabled { get; set; }
    }
}
