//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace dyClawler.Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class resource
    {
        public long ID { get; set; }
        public string ResourceName { get; set; }
        public string ResourceLink { get; set; }
        public string ResourcePassword { get; set; }
        public string ResourceImg { get; set; }
        public bool IsEnable { get; set; }
        public string Remark { get; set; }
        public DateTime CreateTime { get; set; }
        public DateTime LastUpdateTime { get; set; }
        public string DownLoadURLList { get; set; }
        public int MovieType { get; set; }
        public string MovieIntro { get; set; }
        public string OnlineUrl { get; set; }
        public string SoureceDomain { get; set; }
        public DateTime PubDate { get; set; }
    }
}
